# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tensor.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'tensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctensor.proto\x12\ttensor.v1\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\'\n\x06Tensor\x12\r\n\x05shape\x18\x01 \x03(\x03\x12\x0e\n\x06values\x18\x02 \x03(\x01\"7\n\x12\x43heckTensorRequest\x12!\n\x06tensor\x18\x01 \x01(\x0b\x32\x11.tensor.v1.Tensor2\x8f\x01\n\rTensorService\x12=\n\x06Health\x12\x18.tensor.v1.HealthRequest\x1a\x19.tensor.v1.HealthResponse\x12?\n\x0b\x43heckTensor\x12\x1d.tensor.v1.CheckTensorRequest\x1a\x11.tensor.v1.TensorB\x1bZ\x19\x65xample/hello/pb;tensorpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031example/hello/pb;tensorpb'
  _globals['_HEALTHREQUEST']._serialized_start=27
  _globals['_HEALTHREQUEST']._serialized_end=42
  _globals['_HEALTHRESPONSE']._serialized_start=44
  _globals['_HEALTHRESPONSE']._serialized_end=76
  _globals['_TENSOR']._serialized_start=78
  _globals['_TENSOR']._serialized_end=117
  _globals['_CHECKTENSORREQUEST']._serialized_start=119
  _globals['_CHECKTENSORREQUEST']._serialized_end=174
  _globals['_TENSORSERVICE']._serialized_start=177
  _globals['_TENSORSERVICE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
