// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: tensor.proto

package tensorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TensorService_Health_FullMethodName      = "/tensor.v1.TensorService/Health"
	TensorService_CheckTensor_FullMethodName = "/tensor.v1.TensorService/CheckTensor"
)

// TensorServiceClient is the client API for TensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TensorServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	CheckTensor(ctx context.Context, in *CheckTensorRequest, opts ...grpc.CallOption) (*Tensor, error)
}

type tensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTensorServiceClient(cc grpc.ClientConnInterface) TensorServiceClient {
	return &tensorServiceClient{cc}
}

func (c *tensorServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TensorService_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tensorServiceClient) CheckTensor(ctx context.Context, in *CheckTensorRequest, opts ...grpc.CallOption) (*Tensor, error) {
	out := new(Tensor)
	err := c.cc.Invoke(ctx, TensorService_CheckTensor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TensorServiceServer is the server API for TensorService service.
// All implementations must embed UnimplementedTensorServiceServer
// for forward compatibility.
type TensorServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	CheckTensor(context.Context, *CheckTensorRequest) (*Tensor, error)
	mustEmbedUnimplementedTensorServiceServer()
}

// UnimplementedTensorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTensorServiceServer struct{}

func (UnimplementedTensorServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTensorServiceServer) CheckTensor(context.Context, *CheckTensorRequest) (*Tensor, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTensor not implemented")
}
func (UnimplementedTensorServiceServer) mustEmbedUnimplementedTensorServiceServer() {}
func (UnimplementedTensorServiceServer) testEmbeddedByValue()                       {}

// UnsafeTensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TensorServiceServer will
// result in compilation errors.
type UnsafeTensorServiceServer interface {
	mustEmbedUnimplementedTensorServiceServer()
}

func RegisterTensorServiceServer(s grpc.ServiceRegistrar, srv TensorServiceServer) {
	// If the following call panics, it indicates UnimplementedTensorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TensorService_ServiceDesc, srv)
}

func _TensorService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TensorServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TensorService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TensorServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TensorService_CheckTensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TensorServiceServer).CheckTensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TensorService_CheckTensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TensorServiceServer).CheckTensor(ctx, req.(*CheckTensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TensorService_ServiceDesc is the grpc.ServiceDesc for TensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tensor.v1.TensorService",
	HandlerType: (*TensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _TensorService_Health_Handler,
		},
		{
			MethodName: "CheckTensor",
			Handler:    _TensorService_CheckTensor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tensor.proto",
}
